import { Shield, Key, Lock, AlertTriangle, BookOpen, Code } from 'lucide-react'

export default function InfoSection() {
  return (
    <div className="space-y-8">
      {/* What is BIP39 */}
      <section className="bg-surface border border-border rounded-lg p-6">
        <div className="flex items-start gap-4 mb-4">
          <div className="w-10 h-10 bg-primary/10 rounded-lg flex items-center justify-center flex-shrink-0">
            <BookOpen className="w-5 h-5 text-primary" />
          </div>
          <div>
            <h2 className="text-lg font-semibold text-text mb-2">What is BIP39?</h2>
            <p className="text-sm text-textSecondary leading-relaxed">
              BIP39 (Bitcoin Improvement Proposal 39) is a standard for generating deterministic wallets using mnemonic phrases. 
              It converts random entropy into a human-readable sequence of 12-24 words from a standardized wordlist of 2,048 words.
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-6">
          <div className="bg-background/50 border border-border rounded-lg p-4">
            <h3 className="text-sm font-semibold text-text mb-2 flex items-center gap-2">
              <Key className="w-4 h-4 text-primary" />
              How It Works
            </h3>
            <ol className="text-xs text-textSecondary space-y-2 list-decimal list-inside">
              <li>Generate 128-256 bits of random entropy</li>
              <li>Add checksum to entropy</li>
              <li>Divide into 11-bit segments</li>
              <li>Map each segment to BIP39 wordlist</li>
              <li>Derive master seed using PBKDF2</li>
              <li>Generate keys using BIP32 derivation</li>
            </ol>
          </div>

          <div className="bg-background/50 border border-border rounded-lg p-4">
            <h3 className="text-sm font-semibold text-text mb-2 flex items-center gap-2">
              <Code className="w-4 h-4 text-primary" />
              Technical Details
            </h3>
            <ul className="text-xs text-textSecondary space-y-2">
              <li><strong>Wordlist:</strong> 2,048 carefully selected words</li>
              <li><strong>Entropy:</strong> 128 bits (12 words) or 256 bits (24 words)</li>
              <li><strong>Checksum:</strong> Last word contains checksum bits</li>
              <li><strong>Derivation:</strong> PBKDF2-HMAC-SHA512 (2048 rounds)</li>
              <li><strong>Paths:</strong> BIP44 for multi-chain support</li>
            </ul>
          </div>
        </div>
      </section>

      {/* Security Information */}
      <section className="bg-surface border border-border rounded-lg p-6">
        <div className="flex items-start gap-4 mb-4">
          <div className="w-10 h-10 bg-yellow-500/10 rounded-lg flex items-center justify-center flex-shrink-0">
            <Shield className="w-5 h-5 text-yellow-500" />
          </div>
          <div>
            <h2 className="text-lg font-semibold text-text mb-2">Security Considerations</h2>
            <p className="text-sm text-textSecondary leading-relaxed">
              Understanding the security of seed phrases is crucial for cryptocurrency safety.
            </p>
          </div>
        </div>

        <div className="space-y-4 mt-6">
          <div className="bg-background/50 border border-border rounded-lg p-4">
            <h3 className="text-sm font-semibold text-text mb-3">Mathematical Security</h3>
            <div className="space-y-2 text-xs text-textSecondary">
              <p><strong>12-word phrase:</strong> 2^128 possible combinations (340,282,366,920,938,463,463,374,607,431,768,211,456)</p>
              <p><strong>Brute force impossibility:</strong> Even at 1 trillion attempts per second, it would take billions of years to try all combinations</p>
              <p><strong>Comparison:</strong> More combinations than atoms in the observable universe</p>
            </div>
          </div>

          <div className="bg-red-500/10 border border-red-500/20 rounded-lg p-4">
            <h3 className="text-sm font-semibold text-red-400 mb-3 flex items-center gap-2">
              <AlertTriangle className="w-4 h-4" />
              Critical Security Rules
            </h3>
            <ul className="space-y-2 text-xs text-red-200/80 list-disc list-inside">
              <li>Never share your seed phrase with anyone</li>
              <li>Never store seed phrases digitally (photos, cloud, etc.)</li>
              <li>Never enter seed phrases on websites or apps you don't trust</li>
              <li>Never reuse seed phrases generated by tools like this</li>
              <li>Always generate real wallets through official wallet providers</li>
              <li>Store seed phrases on paper in multiple secure locations</li>
            </ul>
          </div>
        </div>
      </section>

      {/* Derivation Paths */}
      <section className="bg-surface border border-border rounded-lg p-6">
        <div className="flex items-start gap-4 mb-4">
          <div className="w-10 h-10 bg-primary/10 rounded-lg flex items-center justify-center flex-shrink-0">
            <Lock className="w-5 h-5 text-primary" />
          </div>
          <div>
            <h2 className="text-lg font-semibold text-text mb-2">Derivation Paths (BIP44)</h2>
            <p className="text-sm text-textSecondary leading-relaxed">
              BIP44 defines a standard derivation path structure: m / purpose' / coin_type' / account' / change / address_index
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mt-6">
          <div className="bg-background/50 border border-border rounded-lg p-4">
            <h3 className="text-sm font-semibold text-text mb-2">Ethereum</h3>
            <code className="text-xs text-primary font-mono block mb-2">m/44'/60'/0'/0/0</code>
            <p className="text-xs text-textSecondary">Coin type: 60</p>
          </div>

          <div className="bg-background/50 border border-border rounded-lg p-4">
            <h3 className="text-sm font-semibold text-text mb-2">Bitcoin</h3>
            <code className="text-xs text-primary font-mono block mb-2">m/84'/0'/0'/0/0</code>
            <p className="text-xs text-textSecondary">Coin type: 0 (SegWit)</p>
          </div>

          <div className="bg-background/50 border border-border rounded-lg p-4">
            <h3 className="text-sm font-semibold text-text mb-2">Solana</h3>
            <code className="text-xs text-primary font-mono block mb-2">m/44'/501'/0'/0'</code>
            <p className="text-xs text-textSecondary">Coin type: 501</p>
          </div>
        </div>
      </section>

      {/* Educational Purpose */}
      <section className="bg-yellow-500/10 border border-yellow-500/20 rounded-lg p-6">
        <div className="flex items-start gap-4">
          <AlertTriangle className="w-6 h-6 text-yellow-500 flex-shrink-0" />
          <div>
            <h2 className="text-lg font-semibold text-yellow-500 mb-2">Educational Research Only</h2>
            <div className="space-y-2 text-sm text-yellow-200/80">
              <p>
                This tool is designed for educational purposes to understand how seed phrases work, the mathematics behind them, 
                and the derivation process for different blockchains.
              </p>
              <p>
                <strong>Never use generated seed phrases for real cryptocurrency wallets.</strong> Always create wallets through 
                official, audited wallet providers (MetaMask, Ledger, Trust Wallet, etc.).
              </p>
              <p>
                The probability of randomly generating a seed phrase that matches an existing funded wallet is astronomically low 
                (effectively impossible), but you should never attempt to use random phrases for accessing real funds.
              </p>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
